version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: student_hours_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_hours
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: student_hours_app
    command: python -m app.main
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    depends_on:
      - mysql
    environment:
      DOCKERIZED: "true"
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: student_hours
    ports:
      - "8000:8000"  # solo si hay  UI web